name: PintoRecipes
version: '1.2'
main: me.pintoadmin.pintoRecipes.PintoRecipes
api-version: '1.21'
authors: [ PintoJ ]

commands:
  pintorecipes:
    usage: /pintorecipes <show|save|edit|list> [recipe_name]
    description: Manage recipes
    permission: pintorecipes.recipes
    aliases: [pr, precipes]